builds:
  - id: "build-linux"
    main: .
    binary: "deltans"
    goos:
      - linux
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    hooks:
      pre: go mod tidy
    env:
      - CGO_ENABLED=0

  - id: "build-windows"
    main: .
    binary: "deltans"
    goos:
      - windows
    goarch:
      - amd64
      - "386"
    hooks:
      pre: go mod tidy
    env:
      - CGO_ENABLED=0
